marzer/tomlplusplus

meson.build
meson_options.txt

* Define tomlplusplus_dep for when included in subproject.
* Added option BUILD_TESTS, default false.

Better support for including as subproject (resolves #11)

---

include/toml++/toml_parser_impl.h
toml.hpp

For some reason, GCC 8.2.0's glibc has the pre-c++11 overloads of `std::string::erase()` which take a non-const iterator. This change fixes building on that compiler, and should also work on later versions (tested with Clang 9.0.1).

Fix build with GCC 8.2.0

---

vs/toml++.natvis

Hello! I've added debug visualizers for `toml::table`, `toml::array`, and the `parse_result` and `parse_error` types that show up when using the non-exceptions build of the library. These mainly just cut down on visual clutter in the watch window.
Here's what a table looks like with the new visualizers:
For comparison, this is what it looked like before:
This is what `parse_result` looks like with a successful parse:
And this is what it looks like with an error:
Hope this is useful to others!

Add more VS debug visualizers

---

include/toml++/toml_node.h
include/toml++/toml_node.hpp
include/toml++/toml_node_view.h
toml.hpp

Hello! I've made a couple of changes to loosen restrictions on the use of `node_view`. Primarily, I added implicit conversion operators from `node` to `node_view` (const and mutable variants). Also, I re-enabled the move assignment operator on `node_view`.
This was motivated by me running into trouble while trying to write code to traverse a table procedurally. Basically, I wanted to do something like this:
```cpp
toml::node_view<const toml::node> child = myTable;
for (auto key : keyPath)
{
child = child[key];
}
```
where I'm descending into a table using a list of keys in `keyPath`.
In opting to do this by adding implicit conversion operators (as opposed to e.g. adding a constructor on `node_view`, or explicit conversion functions), I was guided by `std::string`, which similarly has an …

Add implicit conversion operators from node to node_view

---

examples/utf8_console.h
include/toml++/toml_default_formatter.hpp
tests/manipulating_values.cpp
tests/windows_compat.cpp
toml.hpp

Use lower case header file names for compilation with mingw-w64.

Rename Windows.h to windows.h for mingw-w64

---

include/toml++/toml_array.h
include/toml++/toml_common.h
include/toml++/toml_table.h
tests/meson.build
tests/using_iterators.cpp
toml.hpp

They were missing the iterator_category and thus could not be used with
some standard algorithms.
Making table_iterator and array_iterator usable with standard algorithms and iterator functions.

Make iterators real iterators

---

CMakeLists.txt
cmake/tomlplusplusConfig.cmake
examples/CMakeLists.txt

add simple cmake files to support cmake usage as subproject
optional support install and import of cmake config package files

add cmake files to build and install header only library

---

README.md
include/toml++/toml_default_formatter.hpp
toml.hpp

It bypasses including Windows.h by defining MultiByteToWideChar and WideCharToMultiByte inside an internal winapi namespace.
No, just had a problem with it in my own project, but was marked with a comment inside the code

Bypass including Windows.h (MultiByteToWideChar/WideCharToMultiByte)

---

README.md
docs/pages/main_page.dox

Hi, marzer.
I added new integration instruction for CMake FetchContent in Readme.
Could you review & accept my changes, pls?
Best regards, Proydakov Evgeny.

Added CMake FetchContent information

---

cmake/tomlplusplus.cmake.in

Restores the config file used by Meson that I unknowingly assumed to be unnecessary.
Fixes https://github.com/marzer/tomlplusplus/issues/104

Restore CMake package config used by Meson

---

README.md
cmake/install-rules.cmake

This ensures the natvis file is installed in addition to the header files.
Nope.
Ideally the meson script would also install the natvis file, but I don't anything about meson.
For reference, (by default) this installs it into `<some-install-path>/share/tomlplusplus/toml++.natvis`.

Add natvis file to cmake install rules

---

meson.build

Prevents the headers and pkg-config file from being installed when the library is used as a subproject. 
Another possible approach would be to add a new option for disabling installation, but I don't see how installing a header-only library with the final executable would be useful (headers are only useful for development).
Nope, I directly created a PR instead of creating an issue and fixing it myself. 

build(meson): do not install if used as subproj

---

README.md
examples/meson.build
meson.build
tests/meson.build

Use the `/` operator instead of join_paths
Use the `/` operator instead of using "/" in string paths
Use the `includedir` opt instead of hardcoding "include" in `install_subdir`
Remove discouraged `layout=flat` option (mesonbuild/meson#9243)
Remove unneeded -Wextra, -Wpedantic flags, already added by `warning_level=3`
Remove manual -Oz flag when using Clang (mesonbuild/meson#9286)
Make use of : in kwargs consistent

build(meson): general improvements and fixes

---

meson.build

This improves user experience when using toml++ as a Meson subproject.
With this change users will be able to simply call `dependency('tomlplusplus')` and have Meson automatically resolve the dependency from the subproject if it is not found on the system.
Without this, users always have to explicitly call `dependency('tomlplusplus', fallback: ['tomlplusplus', 'tomlplusplus_dep'])`
A lot of saved keystrokes :)

build(meson): use `override_dependency` if supported

---

include/toml++/impl/parser_impl.h
toml.hpp

Fix a memory leak occuring when value parsing throws an exception. Example on Linux:
```
#include <sstream>
#include <toml++/toml.h>
int main() {
std::stringstream in;
in << "xxx = '\n'";
try {
toml::table tbl = toml::parse(in);
} catch ( ... ) {
}
}
=================================================================
==1701506==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 32 byte(s) in 1 object(s) allocated from:
#0 0xffffb32535b8 in operator new(unsigned long) (/lib/aarch64-linux-gnu/libasan.so.5+0xef5b8)
#1 0xaaaad9ce30cc in __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate(unsigned long, void const*) /usr/include/c++/9/ext/new_allocator.h:114
#2 0xaaaad9ce14ec in …
```

Fix memory leak

---

docs/pages/main_page.dox

I've added the library as a Meson wrap ([see PR](https://github.com/mesonbuild/wrapdb/pull/250)),
and updated the section about installing the library.
Updates the docs with information about the wrap. (I hope I got the formatting correct!)
No

Update docs with information about meson wrap

---

cmake/tomlplusplus.cmake.in
cmake/tomlplusplusConfigVersion.cmake.in
meson.build

Since Meson doesn't yet support CMake's `ARCH_INDEPENDENT` option, a pre-generated Package Version file is installed instead of generating it at configure time.
I've also cleaned up a bit the nearby lines of code.
Fixes #140

build(meson): install CMake Config files to datadir

---

CMakeLists.txt

**What does this change do?** I moved install rules under `PROJECT_IS_TOP_LEVEL` check. Otherwise using `FetchContent` it will generate install rule for this library which is unnecessary since the library is already added to the project.

Move install rules under PROJECT_IS_TOP_LEVEL

---

README.md

Adds a README.md badge for the official toml++ gitter room.

feat: add gitter badge on readme

---

include/toml++/impl/path.h
include/toml++/impl/path.inl
tests/path.cpp
toml.hpp

Improve path_component assignments and safety
#153 

added operator= for path_components to keep component type and value synchronized

---

include/toml++/impl/path.h
include/toml++/impl/path.inl
toml.hpp

Add placement new implementation for paths feature instead of std::variant
#153 

feat(paths): Removed use of std::variant in path_component_value

---

include/meson.build

This changes install directories to more common ones:
.pc --> share/pkgconfig to lib/pkgconfig and libdata/pkgconfig on FreeBSD hosts
.cmake --> share/cmake to lib/cmake

build(meson): Update path for .pc and .cmake files

---

include/meson.build

If you want to read the full story please see pull request #165, but in short moving files from `share/` to `lib/` was needed because FreeBSD didn't look for .pc files in `share/pkgconfig/`.
After a quick [discussion][] upstream, FreeBSD's [pkgconf was patched][] to also honour .pc files in `share/pkgconfig/`.
Now that everybody looks for stuff in `share/`, the commit b1ecdf0ed86faeeaebe13d0db16ad04c20519527 can be reverted, so that stuff like cross-compilation can continue working fine.
[discussion]: https://lists.freebsd.org/archives/freebsd-hackers/2022-July/001355.html
[pkgconf was patched]: https://github.com/freebsd/freebsd-ports/commit/d48fab59daa56e0b3b6ffecef57a69c32ae9c0a7

Revert "build(meson): Update path for .pc and .cmake files (#165)"

---

README.md
include/toml++/impl/path.inl
tests/path.cpp
toml.hpp

Fix seg fault within at_path(toml::path) when there's a missing component
No, new bug identified

Update at_path(toml::path) to handle missing component

---

include/toml++/impl/preprocessor.h
toml.hpp

Solves:
tomlplusplus/include/toml++/impl/path.h:29:73: warning: this condition has identical branches [-Wduplicated-branches]
29 |                                 (alignof(size_t) < alignof(std::string) ? alignof(std::string) : alignof(size_t));
Fix a Warning.
Nope

Suppress -Wduplicated-branches

---

README.md
include/toml++/impl/at_path.inl
tests/path.cpp
toml.hpp

Using a static code analyzer, a suspicious place was discovered:
```cpp
if (c == ']')
{
pos++;
break;
}
else if TOML_UNLIKELY(c == '.' || c == '[')
//                    ^^^^^^^^
break;
else if (c == '\t' || c == '.')
//                    ^^^^^^^^
pos++;
else
return false;
```
Obviously, a mistake was made in one of the places. It is easy to see that in the second case, whitespace characters are checked, so there should be a space (`' '`) instead of a dot (`'.'`). This PR fixing bug, adds a test.
No, I created a PR without creating an issue
[how-to]: …

Fix typo in at_path

---

include/toml++/impl/parser.inl
toml.hpp

Adds `c_str()` for compatibility with mingw, which doesn't have `wstring` overload for `open()`, but does have a `wchar_t *` overload.
Fixes: <https://github.com/marzer/tomlplusplus/issues/182>

fix build with mingw g++ 10

---

include/toml++/impl/header_end.h
include/toml++/impl/header_start.h
toml.hpp

checks if using clang under `header_start.h` and `header_end.h`
Fixes #191 

do not use inline_recursion if using clang

---

.github/workflows/cifuzz.yml
CMakeLists.txt
README.md
fuzzing/CMakeLists.txt
fuzzing/build.sh
fuzzing/toml_fuzzer.cpp

* Introduces a `fuzzing` directory containing a fuzzing harness that targets the `parse` entrypoint and tests the various serializers available in the library.
* Introduces a build script that the OSSFuzz integration will use to build the fuzzer twice a day
* Integrates the fuzzer into the build-system, using a CMake Option called BUILD_FUZZER
Implements #208 
-   [X] I've read [CONTRIBUTING.md]
-   [X] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
-   [X] I've rebuilt and run the tests with …

OSSFuzz integration

---

fuzzing/toml_fuzzer.cpp

Fixes a super simple logic msitake in the harness, where the kMaxValue was set to 1 less than the true max- preventing one branch of the switch from ever being exercised. 
No
-   [X] I've read [CONTRIBUTING.md]
-   [ ] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
-   [X] I've rebuilt and run the tests with at least one of:
-   [X] Clang 8 or higher
-   [X] I've added my name to the list of contributors in …

Resolved bug in kMaxValue in SerializationTest for toml_fuzzer

---

include/toml++/impl/table.hpp

Corrects example in documentation for table.get().
I don't think so.
-   [X] I've read [CONTRIBUTING.md]
-   [X] I've rebased my changes against the current HEAD of `origin/master` (if necessary)
[CONTRIBUTING.md]: …

fix: uses tbl variable name rather than arr in table.get documentation

---

README.md

Update toml-test URL in README from <https://github.com/BurntSushi/toml-test> to <https://github.com/toml-lang/toml-test>. Just make it more formal.
No.
fixing documentation
-   [ ] I've added my name to the list of contributors in …

Update toml-test URL in README

---

README.md
examples/meson.build

This change installs built examples as binaries. 
This might be useful for distribution packagers to provide these example programs in their packages.
N/A
-   [x] GCC 8 or higher
-   [x] I've added my name to the list of contributors in …

feat: install examples for top level builds

---

CMakeLists.txt
cmake/variables.cmake

-   [x] GCC 8 or higher
[how-to]: …

add option `TOMLPLUSPLUS_CPP_INSTALL` to determine whether to install `tomlplusplus`

---

include/toml++/impl/print_to_stream.inl
toml.hpp

With this commit, `std::cout << node.source()` should print both the begin and the end of the source region.
[how-to]: …

let `print_to_stream` also print the end of a source region

---

tests/user_feedback.cpp

Tested commit 1fdd67ce5aab68ab056b9caad4b94ea665753040, "let `print_to_stream` also print the end of a source region (#244)"
-   [x] I've added new test cases to verify my change
[how-to]: …

add unit test for pull request #244 (print end of source region)

---

.github/workflows/cifuzz.yml

- The upload-artifact@v3 is fully deprecated, update to v4.
- Update upload-sarif to v3.
[CONTRIBUTING.md]: …

ci: Update actions to fix fuzzing

---

README.md

Fix some contributors profile link in the README
[CONTRIBUTING.md]: …

docs: Fix some contributors profile link in the README

---

README.md
include/toml++/impl/array.hpp
include/toml++/impl/preprocessor.hpp
include/toml++/impl/table.hpp
toml.hpp

Offered a workaround to compile errors like "error C2057: expected constant expression", when using the "legacy lambda processor" of Visual C++. Such compile errors were reported by Kevin Dick, Jan 19, 2024, at issue #219
-   [x] I've added my name to the list of contributors in [README.md](https://github.com/marzer/tomlplusplus/blob/master/README.md) …

add TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA workaround MSVC error C2057

---

include/toml++/impl/source_region.hpp
tests/user_feedback.cpp
toml.hpp

This pull request adds a utility function, `get_line(doc, line_num)`, which returns the specified line as a `string_view`.
This feature was discussed at issue #254.
-   [x] I've added new test cases to verify my change
-   [x] I've updated any affected documentation
-   [x] I've added my name to the list of contributors in …

add `get_line(doc, line_num)` utility

---

README.md
include/toml++/impl/source_region.hpp
tests/user_feedback.cpp
toml.hpp

**Commit message**
let `toml::get_line` return an _optional_ string_view
Allows users to detect more easily when the specified line number is out of range.
Changes the return type of `get_line` from `string_view` to `optional<string_view>`.
- Aims to supersede pull request #257, following Mark's suggestion at https://github.com/marzer/tomlplusplus/pull/257#issuecomment-2685814256
-   [x] I've added new test cases to verify my change
-   [x] I've updated any affected documentation
-   [x] I've rebuilt …

let `toml::get_line` return an _optional_ string_view

---

examples/error_printer.cpp

It aims to demonstrate a typical use case for `toml::get_line`: printing the source line of a parse error.
- Follow-up to pull request #258.
-   [x] I've added my name to the list of contributors in …

let error_printer example print source line of parse error

---

include/toml++/impl/parser.hpp
include/toml++/impl/path.hpp
tests/tests.hpp
toml.hpp

As discussed in #261, `clang++-20` now nags about a whitespace after the `"""` in `operator""`.  A simple and sufficient change is to remove the whitespace. I have done so in `RcppTOM` and the CRAN repository for R which is already running some checks with `clang++-20` no longer tags the package.
I carried the same change over here.
Note that the embedded `catch` and `nlohmann::json` have the same issue in `operator "" ` (the initial whitespace between `operator` and `""` is apparently permitted) in a handful of places but as this is only used for testing I left it alone.
-   [ ] I've …

Address clang++20 nag about 'whitespace in literal operator'

---

include/toml++/impl/parser.inl
toml.hpp

it fixes a compilation error from windows msys2, because looks like `impl::widen(file_path_str).c_str()` returns a `const wchar_t*` which seems to cause the errors.
I had a workaround to put that TOML_WINDOWS is false and it compiled, so I've decided to remove it.
no
-   [ ] MSVC 19.20 (Visual …

Fix build msys2

---

.github/workflows/ci.yaml
meson.build
meson_options.txt
tests/vs/test_release_x64_legacy_lambda.vcxproj
toml++.sln

The added "test_release_x64_legacy_lambda.vcxproj" is basically just a copy of "test_release_x64.vcxproj", but it has an extra property `ConformanceMode`, set to `Default`. Which triggers MSVC to use its "legacy lambda processor".
With such a configuration, the user may need to define `TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA`.
Update, March 4, 2025: The pull request now also adds `/permissive` builds to the CI, using `TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA` to prevent compile errors.
Follow-up to commit cbc00d6766f14bcd2b3e72de2a3c369a0d48b98a "add TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA workaround MSVC error C2057 (#247)"
-   [x] I've added new test cases to …

test MSVC default conformance mode, using its legacy lambda processor

---

examples/error_printer.cpp

It adds an example case to `invalid_parses` that has a DEL character, and it adjusts the local helper function `print_string` to display this character correctly.
- It's a follow-up to pull request #259
-   [x] I've added my name to the list of …

add DEL character example `invalid_parses` in examples/error_printer

---

README.md

It adds  `TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA` to the table of configurable options, in README.md.
- It's a follow-up to pull request #247
-   [x] I've updated any affected documentation
-   [x] I've added my name to the list of contributors in …

mention `TOML_DISABLE_CONDITIONAL_NOEXCEPT_LAMBDA` in README.md

---

include/toml++/impl/parser.inl
toml.hpp

Changes std::is_trivial to std::is_trivially_default_constructible_v && std::is_trivially_copyable_v.
no.
-   [x] GCC 8 or higher …

fix: std::is_trivial is deprecated in C++26, replace to 'is_trivially_default_constructible_v && is_trivially_copyable_v'.

---

src/modules/tomlpp.cppm

Replaced `toml` with `TOML_NAMESPACE` in the using-declarations in the exported namespace.
Fixed the errors from Visual Studio 2022 version 17.13.5 Compiler Version 19.43.34809 that appeared when building "tomlplusplus_modules", saying:
src\modules\tomlpp.cppm(22,21): error C2872: 'literals': ambiguous symbol
src\modules\tomlpp.cppm(21,22):
could be 'toml::literals'
include\toml++\impl\parser.hpp(322,19):
or       'toml::v3::literals'
src\modules\tomlpp.cppm(22,31): error C2039: '""_toml': is not a member of 'toml::literals'
src\modules\tomlpp.cppm(21,22):
see declaration of 'toml::literals'
src\modules\tomlpp.cppm(22,9): error C2873: '""_toml': symbol cannot be used in a using-declaration
- …

fix MSVC C++20 module build error C2872, C2039, C2873 on 'literals'

---

include/toml++/impl/preprocessor.hpp
include/toml++/impl/value.hpp
toml.hpp

Allowed users of the tomlplusplus module to compile using MSVC.
Without `TOML_DISABLE_NOEXCEPT_NOEXCEPT`, MSVC appears to produce the following error:
> include\toml++\impl\value.hpp(270,39): error C3878: syntax error: unexpected token ',' following 'simple-type-specifier'
>    missing one of: '(' '{' ?
>    include\toml++\impl\value.hpp(270,39):
>    the template instantiation context (the oldest one first) is
>        include\toml++\impl\parser.inl(2757,26):
>        while compiling class template member function 'toml::v3::value<int64_t>::value<int64_t,0>(int64_t &&) noexcept(<expr>)'
- It is another follow-up to pull request #266
- …

TOML_DISABLE_NOEXCEPT_NOEXCEPT workaround MSVC bug noexcept + modules
